{
 "title": "Resource efficiency",
 "description": "This dashboard shows how efficiently requested resources are used in a Kubernetes cluster.",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"},container)"
    }
   },
   { "name": "period", "label": "Period", "query": "1d,2d,4d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Average CPU Requests Usage ($period)",
   "type": "gauge",
   "description": "Average usage of requested CPU by containers over the past $period days.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    sum(\n      rate(\n        container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      [5m])\n    )\n  [$period:])\n  / \n  sum(\n    kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Limits Usage ($period)",
   "type": "gauge",
   "description": "Average usage of CPU limits by containers over the past $period days.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    clamp_min(\n      sum(\n        rate(\n          container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n        [5m])\n      )\n      -\n      sum(\n        kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n      ),\n      0\n    )\n  [$period:])\n  /\n  clamp_min(\n    sum(\n      kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}\n    )\n    -\n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n    ),\n    1\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RAM Requests Usage ($period)",
   "type": "gauge",
   "description": "Average usage of requested RAM by containers over the past $period days.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    sum(\n      container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n    )\n  [$period:])\n  / \n  sum(\n    kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RAM Limits Usage ($period)",
   "type": "gauge",
   "description": "Average usage of RAM limits by containers over the past $period days.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(\n    clamp_min(\n      sum(\n        container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      )\n      -\n      sum(\n        kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n      ),\n      0\n    )\n  [$period:])\n  /\n  clamp_min(\n    sum(\n      kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n    )\n    -\n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n    ),\n    1\n  )\n) * 100\n*\n(\n  (\n    avg_over_time(\n      clamp_min(\n        sum(\n          container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n        )\n        -\n        sum(\n          kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n        ),\n        0\n      )\n    [$period:])\n    /\n    clamp_min(\n      sum(\n        kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n      )\n      -\n      sum(\n        kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n      ),\n      1\n    )\n  )\n  <=\n  1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle in the selected namespace ($period)",
   "type": "bargauge",
   "description": "Average percentage of unused resources in the selected namespace over the past $period days.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  100 - (\n    (\n      quantile_over_time(\n        0.75,\n        sum(\n          rate(\n            container_cpu_usage_seconds_total{namespace=\"$namespace\", pod!=\"\", container!=\"\"}[5m]\n          )\n          *\n          on(namespace, pod, container, uid)\n          group_left\n          sum by (namespace, pod, container) (\n            kube_pod_container_info{namespace=\"$namespace\"} > 0\n          )\n        ) by (namespace)\n      [$period:])\n      /\n      avg_over_time(\n        sum(\n          kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}\n        ) by (namespace)\n      [$period:])\n    )\n    +\n    (\n      quantile_over_time(\n        0.75,\n        sum(\n          container_memory_working_set_bytes{namespace=\"$namespace\", pod!=\"\",container!=\"\"}\n          *\n          on(namespace, pod, container, uid)\n          group_left\n          sum by (namespace, pod, container) (\n            kube_pod_container_info{namespace=\"$namespace\"} > 0\n          )\n        ) by (namespace)\n      [$period:])\n      /\n      avg_over_time(\n        sum(\n          kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}\n        ) by (namespace)\n      [$period:])\n    )\n  ) / 2 * 100,\n  0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Perfect resources ratio ($period)",
   "type": "stat",
   "description": "Perfect resource ratio based on resource consumption data from the past $period days.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "GiB per 1CPU" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    quantile_over_time(\n      0.75,\n      sum(\n        container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      )\n    [$period:]) /1024/1024/1024\n  )\n  /\n  sum(\n    quantile_over_time(\n      0.75,\n      sum(\n        rate(\n          container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n        [5m])\n      )\n    [$period:])\n  )\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Using CPU Requests",
   "type": "timeseries",
   "description": "The percentage of requested CPU used by containers. The graph will show 0 if requests.cpu is not set.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(\n      container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n    [5m])\n  ) by (container, pod, namespace) \n  / \n  sum(\n    kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\"}\n  ) by (container, pod, namespace)\n) * 100",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Using CPU Limits",
   "type": "timeseries",
   "description": "The percentage of CPU usage by containers within limits. The graph will show 0 if limits.cpu is not set or if CPU usage was not higher than requested.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  clamp_min(\n    sum(\n      rate(\n        container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      [5m])\n    ) by (container, pod, namespace)\n    - \n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n    ) by (container, pod, namespace),\n    0\n  )\n)\n/\n(\n  clamp_min(\n    sum(\n      kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n    ) by (container, pod, namespace)\n    -\n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n    ) by (container, pod, namespace),\n    0.001\n  )\n) * 100",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttle Rate (%)",
   "type": "timeseries",
   "description": "Shows the percentage of CPU periods during which the container was throttled, indicating how often it hits its CPU limit.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[5m]\n  )\n) by (namespace, pod, container)\n/\nsum(\n  rate(\n    container_cpu_cfs_periods_total{namespace=\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[5m]\n  )\n) by (namespace, pod, container)\n* 100",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Using RAM Requests",
   "type": "timeseries",
   "description": "The percentage of requested RAM used by containers. The graph will show 0 if requests.memory is not set.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n  ) by (container, pod, namespace) \n  / \n  sum(\n    kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}\n  ) by (container, pod, namespace)\n) * 100",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Using RAM Limits",
   "type": "timeseries",
   "description": "The percentage of RAM usage by containers within limits. The graph will show 0 if limits.memory is not set or if RAM usage was not higher than requested.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  clamp_min(\n    sum(\n      container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n    ) by (container, pod, namespace)\n    -\n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n    ) by (container, pod, namespace),\n    0\n  )\n  /\n  clamp_min(\n    sum(\n      kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n    ) by (container, pod, namespace)\n    -\n    sum(\n      kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n    ) by (container, pod, namespace),\n    1\n  )\n) * 100",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Resource recommendations by container parent ($period)",
   "type": "table",
   "description": "Current and recommended resource requests and limits on containers.",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n  * 1000\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  clamp_min(\n    quantile_over_time(\n      0.75,\n      rate(\n        container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      [5m])\n    [$period:]) * 1000,\n    10\n  )\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  clamp_min(\n    quantile_over_time(\n      0.95,\n      sum(\n        container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      ) by (container, pod, namespace)\n    [$period:]),\n    10485760\n  )\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n  * 1000\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  (\n    avg(\n      clamp_min(\n        quantile_over_time(\n          0.95,\n          rate(\n            container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n          [5m])\n        [$period:]) * 1000,\n        10\n      )\n    ) by (namespace, pod, container)\n    +\n    (\n      (\n        sum(\n          kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n        ) by (namespace, pod, container) * 1000\n        * 1\n      )\n      *\n      (\n        1\n        -\n        exp(\n          -155\n          *\n          quantile_over_time(\n            0.95,\n            (\n              sum(\n                rate(\n                  container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]\n                )\n              ) by (namespace, pod, container)\n              /\n              clamp_min(\n                sum(\n                  rate(\n                    container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]\n                  )\n                ) by (namespace, pod, container),\n                1\n              )\n            )[$period:]\n          )\n        )\n      )\n    )\n    +\n    (\n      (\n        sum(\n          kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}\n        ) by (namespace, pod, container) * 1000\n        * 3\n      )\n      *\n      (\n        1\n        -\n        exp(\n          -4\n          *\n          quantile_over_time(\n            0.95,\n            (\n              sum(\n                rate(\n                  container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]\n                )\n              ) by (namespace, pod, container)\n              /\n              clamp_min(\n                sum(\n                  rate(\n                    container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m]\n                  )\n                ) by (namespace, pod, container),\n                1\n              )\n            )[$period:]\n          )\n        )\n      )\n    )\n  )\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\"}\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace, owner_kind, owner_name, container) (\n  clamp_min(\n    quantile_over_time(\n      0.98,\n      sum(\n        container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n      ) by (container, pod, namespace)\n    [$period:]) * 1.1,\n    10485760\n  )\n  *\n  on(namespace, pod)\n  group_left(owner_kind, owner_name)\n  kube_pod_owner{namespace=\"$namespace\", pod=~\"$pod\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}